=== ivanov-gv/cg-map/packages/contracts/transit-network.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Representative bus route network v1",
  "type": "object",
  "required": [
    "version",
    "retrievedAt",
    "source",
    "stops",
    "patterns"
  ],
  "properties": {
    "version": {
      "const": 1
    },
    "retrievedAt": {
      "type": "string",
      "format": "date-time"
    },
    "source": {
      "type": "string"
    },
    "stops": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "required": [
          "name",
          "coordinates"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "coordinates": {
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
              "type": "number"
            }
          }
        }
      }
    },
    "patterns": {
      "type": "array",
      "minItems": 1,
      "maxItems": 500,
      "items": {
        "type": "object",
        "required": [
          "route",
          "name",
          "headsign",
          "stops",
          "offsets"
        ],
        "properties": {
          "route": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string"
          },
          "headsign": {
            "type": "string"
          },
          "stops": {
            "type": "array",
            "minItems": 2,
            "maxItems": 300,
            "items": {
              "type": "string"
            }
          },
          "offsets": {
            "type": "array",
            "minItems": 2,
            "maxItems": 300,
            "items": {
              "type": "number",
              "minimum": 0,
              "maximum": 172800
            }
          }
        }
      }
    }
  }
}

=== ivanov-gv/cg-map/data/sources/transit-network.json
{"version":1,"retrievedAt":"2026-10-18T19:54:19.226051+00:00","source":"https://epodgorica.me/javniprevoz/mapa","stops":{"1":{"name":"Ul. 13. jula (B)","coordinates":[19.254951,42.446057]},"10":{"name":"Gradski stadion (B)","coordinates":[19.26345,42.443523]},"100":{"name":"Blok 6 (ispred Tološke šume) (A)","coordinates":[19.23780355,42.44677918]},"101":{"name":"Delta City I (B)","coordinates":[19.235967,42.438187]},"103":{"name":"OŠ Marko Miljanov (B)","coordinates":[19.28249381,42.43850234]},"105":{"name":"Kamionska pijaca (B)","coordinates":[19.268941,42.42334]},"106":{"name":"27. marta I (B)","coordinates":[19.246381,42.426419]},"107":{"name":"Goce Delčeva (B)","coordinates":[19.281752,42.442347]},"108":{"name":"Skopska I (B)","coordinates":[19.281987,42.445683]},"109":{"name":"Bivša kasarna Masline (B)","coordinates":[19.28468596,42.44195132]},"11":{"name":"Pozorište (A)","coordinates":[19.26066935,42.44271848]},"110":{"name":"Tološi II (A)","coordinates":[19.2275843,42.44989616]},"111":{"name":"Tološi I (B)","coordinates":[19.23288168,42.44812047]},"112":{"name":"Vrela ribnička (B)","coordinates":[19.2943961,42.43434813]},"113":{"name":"Mitra Bakića (A)","coordinates":[19.26711202,42.43203704]},"115":{"name":"Vojvode Ilije Plamenca I (A)","coordinates":[19.243516,42.431946]},"117":{"name":"Velika pijaca (B)","coordinates":[19.262306,42.432722]},"118":{"name":"Stadion FK Kom (B)","coordinates":[19.296022,42.465006]},"119":{"name":"Ul. 4. jula III (B)","coordinates":[19.260022,42.428611]},"12":{"name":"Medicinska škola (A)","coordinates":[19.249407,42.436883]},"120":{"name":"Bivša kasarna Masline (A)","coordinates":[19.285242,42.441734]},"121":{"name":"KBC (A)","coordinates":[19.245366,42.438717]},"122":{"name":"Zgrada Vektre (B)","coordinates":[19.247621,42.4417]},"123":{"name":"Nikšićki put II (B)","coordinates":[19.22004949,42.43961122]},"124":{"name":"Vatrogasna (A)","coordinates":[19.267886,42.424433]},"125":{"name":"Blok 5 I (B)","coordinates":[19.246092,42.445767]},"126":{"name":"Capital plaza II (A)","coordinates":[19.240815,42.440302]},"128":{"name":"Bracana Bracanovića (B)","coordinates":[19.262371,42.428678]},"129":{"name":"Pozorište (B)","coordinates":[19.259703,42.441434]},"13":{"name":"Orjenska III (A)","coordinates":[19.293815,42.457055]},"130":{"name":"Bulevar Ivana Crnojevića I (B)","coordinates":[19.27056,42.441612]},"131":{"name":"Boška Buhe I (B)","coordinates":[19.232607,42.455509]},"132":{"name":"Ul. Oktobarske revolucije II (A)","coordinates":[19.26265419,42.43500253]},"133":{"name":"Španskih boraca I (A)","coordinates":[19.30042516,42.42637572]},"134":{"name":"Stadion Tološi (A)","coordinates":[19.22411176,42.45102225]},"135":{"name":"Elektrodistribucija (A)","coordinates":[19.254219,42.440425]},"136":{"name":"Delta City I (A)","coordinates":[19.234309,42.43775]},"137":{"name":"OŠ Marko Miljanov (A)","coordinates":[19.28224504,42.43856172]},"14":{"name":"Capital plaza III (A)","coordinates":[19.2402792,42.43934163]},"142":{"name":"Milana Raičkovića III (A)","coordinates":[19.223632,42.454986]},"143":{"name":"Donja Gorica - hotel (B)","coordinates":[19.200574,42.418573]},"144":{"name":"Milana Raičkovića II (B)","coordinates":[19.225997,42.454406]},"145":{"name":"Stadion Tološi (B)","coordinates":[19.22452393,42.45080081]},"147":{"name":"Capital plaza I (A)","coordinates":[19.244021,42.440194]},"148":{"name":"Meše Selimović (B)","coordinates":[19.238652,42.447591]},"149":{"name":"Blok 5 - zadnja zgrada (B)","coordinates":[19.240503,42.450121]},"15":{"name":"Orjenska IV (A)","coordinates":[19.295913,42.458693]},"150":{"name":"Blok 5 (žuta zgrada) (B)","coordinates":[19.24320817,42.44870769]},"151":{"name":"Orjenska IV (B)","coordinates":[19.295809,42.458714]},"155":{"name":"Partizanski put III (A)","coordinates":[19.199966,42.458007]},"156":{"name":"Donja Gorica III (B)","coordinates":[19.212595,42.419916]},"157":{"name":"Kakaricka gora - vrt (A)","coordinates":[19.304106,42.445188]},"158":{"name":"Tološko groblje I (B)","coordinates":[19.213855,42.454935]},"159":{"name":"Španskih boraca II (A)","coordinates":[19.29797899,42.42968596]},"160":{"name":"Španskih boraca I (B)","coordinates":[19.2995299,42.42723982]},"161":{"name":"Bulevar Revolucije (B)","coordinates":[19.24863696,42.44046991]},"163":{"name":"Gornja Gorica (B)","coordinates":[19.225613,42.434072]},"166":{"name":"Donja Gorica I (B)","coordinates":[19.221122,42.425491]},"167":{"name":"Janka Đonovića I (B)","coordinates":[19.24394315,42.41833459]},"169":{"name":"Manastirska II (B)","coordinates":[19.241863,42.405481]},"17":{"name":"Franca Rozmana I (B)","coordinates":[19.287732,42.453472]},"170":{"name":"Dalmatinska II (A)","coordinates":[19.243485,42.449174]},"171":{"name":"Milana Raičkovića (B)","coordinates":[19.230237,42.453132]},"172":{"name":"Office centar (A)","coordinates":[19.292789,42.435948]},"173":{"name":"Zgrada Vektre (A)","coordinates":[19.247515,42.441781]},"174":{"name":"Tološi I (A)","coordinates":[19.231862,42.448606]},"175":{"name":"Gornja Gorica II (A)","coordinates":[19.218321,42.438262]},"176":{"name":"Gornja Gorica II (B)","coordinates":[19.218464,42.438159]},"177":{"name":"Ul. Iva Andrića - škola (A)","coordinates":[19.2743862,42.45462231]},"18":{"name":"Gornja Gorica III (B)","coordinates":[19.220817,42.435601]},"180":{"name":"27. marta I (A)","coordinates":[19.247664,42.425926]},"181":{"name":"Boška Buhe I (A)","coordinates":[19.232299,42.455259]},"182":{"name":"Dom zdravlja Pobrežje (B)","coordinates":[19.259059,42.430477]},"183":{"name":"Milana Raičkovića I (B)","coordinates":[19.228241,42.453884]},"184":{"name":"Bulevar Revolucije (A)","coordinates":[19.24858868,42.44060451]},"185":{"name":"Donja Gorica II (B)","coordinates":[19.215677,42.421942]},"186":{"name":"V Proleterske brigade (B)","coordinates":[19.269658,42.4373]},"19":{"name":"Stanica prve pomoći (A)","coordinates":[19.261695,42.444877]},"190":{"name":"Milana Raičkovića IV (A)","coordinates":[19.219901,42.455314]},"191":{"name":"Kralja Nikole (B)","coordinates":[19.255466,42.426483]},"192":{"name":"Spomenik (B)","coordinates":[19.289277,42.448589]},"193":{"name":"Tološko groblje (A)","coordinates":[19.215793,42.454186]},"194":{"name":"Mojkovačka (B)","coordinates":[19.277092,42.437177]},"195":{"name":"Tološi II (B)","coordinates":[19.227995,42.449712]},"196":{"name":"Ul. Nikole Tesle II (A)","coordinates":[19.273375,42.460264]},"197":{"name":"OŠ Pavle Rovinski (B)","coordinates":[19.2757273,42.42731652]},"198":{"name":"Cijevna (B)","coordinates":[19.297837,42.399892]},"199":{"name":"IX Crnogorske brigade (A)","coordinates":[19.270839,42.454445]},"2":{"name":"Ul. II Crnogorskog bataljona (B)","coordinates":[19.26498,42.455609]},"20":{"name":"Ul. II Crnogorskog bataljona (A)","coordinates":[19.264891,42.455438]},"200":{"name":"Most Braće Zlatičanin (B)","coordinates":[19.261931,42.438499]},"201":{"name":"Trg Golootočkih žrtava (B)","coordinates":[19.26826,42.43257947]},"202":{"name":"Ul. Oktobarske revolucije I (A)","coordinates":[19.2646873,42.43442053]},"203":{"name":"Konik (A)","coordinates":[19.3018949,42.42465834]},"204":{"name":"Vrela ribnička (A)","coordinates":[19.29425424,42.43476385]},"205":{"name":"Mojkovačka (A)","coordinates":[19.27763164,42.43718004]},"206":{"name":"Blok 5 - benz. pumpa (A)","coordinates":[19.245639,42.447434]},"207":{"name":"Elastik (B)","coordinates":[19.22005835,42.45217934]},"209":{"name":"Orjenska II (B)","coordinates":[19.292459,42.45607]},"21":{"name":"Ul. Nikole Tesle I (A)","coordinates":[19.269394,42.458118]},"213":{"name":"Vojvode Ilije Plamenca I (B)","coordinates":[19.243959,42.430762]},"214":{"name":"Goce Delčeva (A)","coordinates":[19.282006,42.442362]},"215":{"name":"Dalmatinska III (A)","coordinates":[19.241362,42.450488]},"216":{"name":"Bulevar Svetog Petra Cetinjskog I (B)","coordinates":[19.252771,42.441624]},"217":{"name":"Milana Raičkovića I (A)","coordinates":[19.228084,42.453967]},"218":{"name":"Partizanski put III (B)","coordinates":[19.199985,42.457902]},"220":{"name":"Španskih boraca II (B)","coordinates":[19.29808628,42.4292029]},"223":{"name":"Mala pijaca (A)","coordinates":[19.24983,42.445825]},"224":{"name":"Soliteri Zabjelo (B)","coordinates":[19.251939,42.423937]},"225":{"name":"Milana Raičkovića IV (B)","coordinates":[19.220225,42.455275]},"226":{"name":"Tološko groblje (B)","coordinates":[19.2159462,42.45404326]},"227":{"name":"Trg Božane Vučinić","coordinates":[19.26256835,42.43649908]},"228":{"name":"Tržni centar (B)","coordinates":[19.27918063,42.43144076]},"229":{"name":"27. marta II (B)","coordinates":[19.255498,42.423571]},"23":{"name":"Orjenska","coordinates":[19.288639,42.453329]},"230":{"name":"Cijevna (A)","coordinates":[19.298512,42.398997]},"234":{"name":"Milana Raičkovića II (A)","coordinates":[19.226425,42.454336]},"235":{"name":"Skopska II (B)","coordinates":[19.278355,42.443457]},"236":{"name":"Soliteri I (B)","coordinates":[19.25888,42.449459]},"237":{"name":"Ul. Oktobarske revolucije I (B)","coordinates":[19.26511157,42.43419723]},"238":{"name":"Blok 5 - zadnja zgrada (A)","coordinates":[19.240775,42.450118]},"239":{"name":"Ul. Braće Ribar I (A)","coordinates":[19.286476,42.438466]},"24":{"name":"Manastirska II (A)","coordinates":[19.241602,42.405345]},"240":{"name":"Elektrodistribucija (B)","coordinates":[19.254295,42.440319]},"242":{"name":"Nikšićki put I (B)","coordinates":[19.227035,42.436628]},"243":{"name":"Ul. Nikole Tesle III (A)","coordinates":[19.275598,42.460561]},"244":{"name":"Pasarela (B)","coordinates":[19.293246,42.461827]},"246":{"name":"V Proleterske brigade (A)","coordinates":[19.269349,42.437458]},"247":{"name":"Mitra Bakića (B)","coordinates":[19.26695645,42.43211227]},"252":{"name":"MUP garaža (A)","coordinates":[19.26416255,42.45597155]},"253":{"name":"Kamenica (A)","coordinates":[19.116508,42.390125]},"254":{"name":"Orjenska V (B)","coordinates":[19.29875672,42.46085455]},"256":{"name":"Limenka (A)","coordinates":[19.28435422,42.46
